# Generated by Django 4.0.3 on 2022-04-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_help_alter_productimage_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotype', models.ImageField(upload_to='static/images/')),
                ('info', models.TextField()),
                ('id_header', models.IntegerField()),
                ('number', models.IntegerField(choices=[(0, 'Number'), (1, 'Email'), (2, 'Instagram'), (3, 'Telegram'), (4, 'WhatsApp')])),
                ('email', models.URLField(choices=[(0, 'Number'), (1, 'Email'), (2, 'Instagram'), (3, 'Telegram'), (4, 'WhatsApp')])),
                ('instagram', models.URLField(choices=[(0, 'Number'), (1, 'Email'), (2, 'Instagram'), (3, 'Telegram'), (4, 'WhatsApp')])),
                ('telegram', models.URLField(choices=[(0, 'Number'), (1, 'Email'), (2, 'Instagram'), (3, 'Telegram'), (4, 'WhatsApp')])),
                ('whatsapp', models.URLField(choices=[(0, 'Number'), (1, 'Email'), (2, 'Instagram'), (3, 'Telegram'), (4, 'WhatsApp')])),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
