# Generated by Django 4.0.3 on 2022-04-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_backcall_floatingbutton_footer_statuscall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floatingbutton',
            name='telegram',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='floatingbutton',
            name='whatsapp',
            field=models.CharField(max_length=150),
        ),
    ]
