# Generated by Django 4.0.3 on 2022-04-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_footer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='email',
            field=models.CharField(choices=[(0, 'Number'), (1, 'Email'), (2, 'Instagram'), (3, 'Telegram'), (4, 'WhatsApp')], max_length=100),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.CharField(choices=[(0, 'Number'), (1, 'Email'), (2, 'Instagram'), (3, 'Telegram'), (4, 'WhatsApp')], max_length=100),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telegram',
            field=models.CharField(choices=[(0, 'Number'), (1, 'Email'), (2, 'Instagram'), (3, 'Telegram'), (4, 'WhatsApp')], max_length=100),
        ),
        migrations.AlterField(
            model_name='footer',
            name='whatsapp',
            field=models.IntegerField(choices=[(0, 'Number'), (1, 'Email'), (2, 'Instagram'), (3, 'Telegram'), (4, 'WhatsApp')]),
        ),
    ]
